[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=lib/forge-std/src/"
]
test = 'test/foundry'
solc_version = '0.8.20'
